/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment03;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Library library =
                new Library();

        Book book =
            new Book(
                "B01",
                "Lap Trinh Java OOP",
                "NGOC ANH",
                2022,
                10);

        Reader reader =
            new Reader(
                "R01",
                "Le Linh Chi",
                "chi@gmail.com",
                ReaderType.STUDENT);

        library.addBook(book);

        library.addReader(reader);

        library.searchBook("Java");
    
    }
}
