/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment03;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void showAllReadersAndLateFeesShouldUsePolymorphism() {
        Library lib = new Library();
        lib.addReader(new Student("R01", "Le Van C", "c@student.edu"));
        lib.addReader(new Lecturer("R02", "Pham Thi D", "d@uni.edu"));

        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(buffer));
        try {
            lib.showAllReaders();
            lib.showLateFees(7);
        } finally {
            System.setOut(originalOut);
        }

        String output = buffer.toString();
        assertTrue(output.contains("[SV]"), "expected student info tag");
        assertTrue(output.contains("[GV]"), "expected lecturer info tag");
        assertTrue(output.contains("14,000"), "expected student late fee");
        assertTrue(output.contains("7,000"), "expected lecturer late fee");
    }
}
